version: '3'

services: 

  nginx:
    build: 
      context: ./nginx
    image: gustavomelloti/nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    command: --init-file /data/application/init.sql
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      